#ifndef CPU_HPP
#define CPU_HPP
#include <cstdint>
#include <functional>
#include <memory>
#include <vector>
#include <string>

class Bus;
class PPU;
class APU;
class CPU {
        public:
                explicit CPU();
                void step();
                void connect_to_bus(const std::shared_ptr<Bus>& bus) noexcept;
                void connect_to_ppu(const std::shared_ptr<PPU>& ppu) noexcept;
                void connect_to_apu(const std::shared_ptr<APU>& apu) noexcept;
                float get_internal_audio_accumulator() const noexcept { return internal_audio_accumulator;}
                void set_internal_audio_accumulator(float new_val) noexcept {internal_audio_accumulator = new_val;}
        private:
                void update_timers(unsigned int t_cycles);
                void handle_interrupt();

                std::uint8_t fetch_byte();
                std::uint16_t fetch_word();
                void push_word(std::uint16_t word);
                std::uint16_t pop_word();

                void _load_8_bit_reg(std::uint8_t& reg, std::uint8_t operand);
                void _load_16_bit_reg(std::uint16_t& reg, std::uint16_t operand);
                void _inc_8_bit_reg(std::uint8_t& reg);
                void _inc_16_bit_reg(std::uint16_t& reg);
                void _dec_8_bit_reg(std::uint8_t& reg);
                void _dec_16_bit_reg(std::uint16_t& reg);
                void _add_8_bit_reg(std::uint8_t& operand_1, std::uint8_t& operand_2);
                void _add_16_bit_reg(std::uint16_t& operand_1, std::uint16_t& operand_2);
                void _adc(std::uint8_t& operand_1, std::uint8_t& operand_2);
                void _sub(std::uint8_t& operand_1, std::uint8_t& operand_2);
                void _sbc(std::uint8_t& operand_1, std::uint8_t& operand_2);
                void _and(std::uint8_t& operand_1, std::uint8_t& operand_2);
                void _xor(std::uint8_t& operand_1, std::uint8_t& operand_2);
                void _or(std::uint8_t& operand_1, std::uint8_t& operand_2);
                void _cp(std::uint8_t& operand_1, std::uint8_t& operand_2);
                void _jr(std::uint8_t operand, bool condition);
                void _jp(std::uint16_t operand, bool condition);
                void _call(std::uint16_t operand, bool condition);
                void _ret(bool condition);
                void _rst(std::uint8_t operand);


                void cb_rlc(std::uint8_t& reg);
                void cb_rrc(std::uint8_t& reg);
                void cb_rl(std::uint8_t& reg);
                void cb_rr(std::uint8_t& reg);
                void cb_sla(std::uint8_t& reg);
                void cb_sra(std::uint8_t& reg);
                void cb_swap(std::uint8_t& reg);
                void cb_srl(std::uint8_t& reg);
                void cb_bit(std::uint8_t& reg, std::uint8_t n_bit);
                void cb_res(std::uint8_t& reg, std::uint8_t n_bit);
                void cb_set(std::uint8_t& reg, std::uint8_t n_bit);

                void nop();
                void load_bc();
                void load_addr_bc_a();
                void inc_bc();
                void inc_b();
                void dec_b();
                void load_b();
                void rlca();
                void load_addr_sp();
                void add_hl_bc();
                void load_a_addr_bc();
                void dec_bc();
                void inc_c();
                void dec_c();
                void load_c();
                void rrca();
                void stop();
                void load_de();
                void load_addr_de_a();
                void inc_de();
                void inc_d();
                void dec_d();
                void load_d();
                void rla();
                void jr();
                void add_hl_de();
                void load_a_addr_de();
                void dec_de();
                void inc_e();
                void dec_e();
                void load_e();
                void rra();
                void jr_nz();
                void load_hl();
                void load_addr_hl_plus_a();
                void inc_hl();
                void inc_h();
                void dec_h();
                void load_h();
                void daa();
                void jr_z();
                void add_hl_hl();
                void load_a_addr_hl_plus();
                void dec_hl();
                void inc_l();
                void dec_l();
                void load_l();
                void cpl();
                void jr_nc();
                void load_sp();
                void load_addr_hl_minus_a();
                void inc_sp();
                void inc_addr_hl();
                void dec_addr_hl();
                void load_addr_hl();
                void scf();
                void jr_c();
                void add_hl_sp();
                void load_a_addr_hl_minus();
                void dec_sp();
                void inc_a();
                void dec_a();
                void load_a();
                void ccf();
                void load_b_b();
                void load_b_c();
                void load_b_d();
                void load_b_e();
                void load_b_h();
                void load_b_l();
                void load_b_addr_hl();
                void load_b_a();
                void load_c_b();
                void load_c_c();
                void load_c_d();
                void load_c_e();
                void load_c_h();
                void load_c_l();
                void load_c_addr_hl();
                void load_c_a();
                void load_d_b();
                void load_d_c();
                void load_d_d();
                void load_d_e();
                void load_d_h();
                void load_d_l();
                void load_d_addr_hl();
                void load_d_a();
                void load_e_b();
                void load_e_c();
                void load_e_d();
                void load_e_e();
                void load_e_h();
                void load_e_l();
                void load_e_addr_hl();
                void load_e_a();
                void load_h_b();
                void load_h_c();
                void load_h_d();
                void load_h_e();
                void load_h_h();
                void load_h_l();
                void load_h_addr_hl();
                void load_h_a();
                void load_l_b();
                void load_l_c();
                void load_l_d();
                void load_l_e();
                void load_l_h();
                void load_l_l();
                void load_l_addr_hl();
                void load_l_a();
                void load_addr_hl_b();
                void load_addr_hl_c();
                void load_addr_hl_d();
                void load_addr_hl_e();
                void load_addr_hl_h();
                void load_addr_hl_l();
                void halt();
                void load_addr_hl_a();
                void load_a_b();
                void load_a_c();
                void load_a_d();
                void load_a_e();
                void load_a_h();
                void load_a_l();
                void load_a_addr_hl();
                void load_a_a();
                void add_a_b();
                void add_a_c();
                void add_a_d();
                void add_a_e();
                void add_a_h();
                void add_a_l();
                void add_a_addr_hl();
                void add_a_a();
                void adc_a_b();
                void adc_a_c();
                void adc_a_d();
                void adc_a_e();
                void adc_a_h();
                void adc_a_l();
                void adc_a_addr_hl();
                void adc_a_a();
                void sub_a_b();
                void sub_a_c();
                void sub_a_d();
                void sub_a_e();
                void sub_a_h();
                void sub_a_l();
                void sub_a_addr_hl();
                void sub_a_a();
                void sbc_a_b();
                void sbc_a_c();
                void sbc_a_d();
                void sbc_a_e();
                void sbc_a_h();
                void sbc_a_l();
                void sbc_a_addr_hl();
                void sbc_a_a();
                void and_a_b();
                void and_a_c();
                void and_a_d();
                void and_a_e();
                void and_a_h();
                void and_a_l();
                void and_a_addr_hl();
                void and_a_a();
                void xor_a_b();
                void xor_a_c();
                void xor_a_d();
                void xor_a_e();
                void xor_a_h();
                void xor_a_l();
                void xor_a_addr_hl();
                void xor_a_a();
                void or_a_b();
                void or_a_c();
                void or_a_d();
                void or_a_e();
                void or_a_h();
                void or_a_l();
                void or_a_addr_hl();
                void or_a_a();
                void cp_a_b();
                void cp_a_c();
                void cp_a_d();
                void cp_a_e();
                void cp_a_h();
                void cp_a_l();
                void cp_a_addr_hl();
                void cp_a_a();
                void ret_nz();
                void pop_bc();
                void jp_nz();
                void jp();
                void call_nz();
                void push_bc();
                void add_a();
                void rst_00h();
                void ret_z();
                void ret();
                void jp_z();
                void prefix();
                void call_z();
                void call();
                void adc_a();
                void rst_08h();
                void ret_nc();
                void pop_de();
                void jp_nc();
                void call_nc();
                void push_de();
                void sub_a();
                void rst_10h();
                void ret_c();
                void reti();
                void jp_c();
                void call_c();
                void sbc_a();
                void rst_18h();
                void ldh_addr_a();
                void pop_hl();
                void ldh_addr_c_a();
                void push_hl();
                void and_a();
                void rst_20h();
                void add_sp();
                void jp_hl();
                void load_addr_a();
                void xor_a();
                void rst_28h();
                void ldh_a_addr();
                void pop_af();
                void ldh_a_addr_c();
                void di();
                void push_af();
                void or_a();
                void rst_30h();
                void load_hl_sp_add();
                void load_sp_hl();
                void load_a_addr();
                void ei();
                void cp_a();
                void rst_38h();

                void cb_rlc_b();
                void cb_rlc_c();
                void cb_rlc_d();
                void cb_rlc_e();
                void cb_rlc_h();
                void cb_rlc_l();
                void cb_rlc_addr_hl();
                void cb_rlc_a();
                void cb_rrc_b();
                void cb_rrc_c();
                void cb_rrc_d();
                void cb_rrc_e();
                void cb_rrc_h();
                void cb_rrc_l();
                void cb_rrc_addr_hl();
                void cb_rrc_a();
                void cb_rl_b();
                void cb_rl_c();
                void cb_rl_d();
                void cb_rl_e();
                void cb_rl_h();
                void cb_rl_l();
                void cb_rl_addr_hl();
                void cb_rl_a();
                void cb_rr_b();
                void cb_rr_c();
                void cb_rr_d();
                void cb_rr_e();
                void cb_rr_h();
                void cb_rr_l();
                void cb_rr_addr_hl();
                void cb_rr_a();
                void cb_sla_b();
                void cb_sla_c();
                void cb_sla_d();
                void cb_sla_e();
                void cb_sla_h();
                void cb_sla_l();
                void cb_sla_addr_hl();
                void cb_sla_a();
                void cb_sra_b();
                void cb_sra_c();
                void cb_sra_d();
                void cb_sra_e();
                void cb_sra_h();
                void cb_sra_l();
                void cb_sra_addr_hl();
                void cb_sra_a();
                void cb_swap_b();
                void cb_swap_c();
                void cb_swap_d();
                void cb_swap_e();
                void cb_swap_h();
                void cb_swap_l();
                void cb_swap_addr_hl();
                void cb_swap_a();
                void cb_srl_b();
                void cb_srl_c();
                void cb_srl_d();
                void cb_srl_e();
                void cb_srl_h();
                void cb_srl_l();
                void cb_srl_addr_hl();
                void cb_srl_a();
                void cb_bit_0_b();
                void cb_bit_0_c();
                void cb_bit_0_d();
                void cb_bit_0_e();
                void cb_bit_0_h();
                void cb_bit_0_l();
                void cb_bit_0_addr_hl();
                void cb_bit_0_a();
                void cb_bit_1_b();
                void cb_bit_1_c();
                void cb_bit_1_d();
                void cb_bit_1_e();
                void cb_bit_1_h();
                void cb_bit_1_l();
                void cb_bit_1_addr_hl();
                void cb_bit_1_a();
                void cb_bit_2_b();
                void cb_bit_2_c();
                void cb_bit_2_d();
                void cb_bit_2_e();
                void cb_bit_2_h();
                void cb_bit_2_l();
                void cb_bit_2_addr_hl();
                void cb_bit_2_a();
                void cb_bit_3_b();
                void cb_bit_3_c();
                void cb_bit_3_d();
                void cb_bit_3_e();
                void cb_bit_3_h();
                void cb_bit_3_l();
                void cb_bit_3_addr_hl();
                void cb_bit_3_a();
                void cb_bit_4_b();
                void cb_bit_4_c();
                void cb_bit_4_d();
                void cb_bit_4_e();
                void cb_bit_4_h();
                void cb_bit_4_l();
                void cb_bit_4_addr_hl();
                void cb_bit_4_a();
                void cb_bit_5_b();
                void cb_bit_5_c();
                void cb_bit_5_d();
                void cb_bit_5_e();
                void cb_bit_5_h();
                void cb_bit_5_l();
                void cb_bit_5_addr_hl();
                void cb_bit_5_a();
                void cb_bit_6_b();
                void cb_bit_6_c();
                void cb_bit_6_d();
                void cb_bit_6_e();
                void cb_bit_6_h();
                void cb_bit_6_l();
                void cb_bit_6_addr_hl();
                void cb_bit_6_a();
                void cb_bit_7_b();
                void cb_bit_7_c();
                void cb_bit_7_d();
                void cb_bit_7_e();
                void cb_bit_7_h();
                void cb_bit_7_l();
                void cb_bit_7_addr_hl();
                void cb_bit_7_a();
                void cb_res_0_b();
                void cb_res_0_c();
                void cb_res_0_d();
                void cb_res_0_e();
                void cb_res_0_h();
                void cb_res_0_l();
                void cb_res_0_addr_hl();
                void cb_res_0_a();
                void cb_res_1_b();
                void cb_res_1_c();
                void cb_res_1_d();
                void cb_res_1_e();
                void cb_res_1_h();
                void cb_res_1_l();
                void cb_res_1_addr_hl();
                void cb_res_1_a();
                void cb_res_2_b();
                void cb_res_2_c();
                void cb_res_2_d();
                void cb_res_2_e();
                void cb_res_2_h();
                void cb_res_2_l();
                void cb_res_2_addr_hl();
                void cb_res_2_a();
                void cb_res_3_b();
                void cb_res_3_c();
                void cb_res_3_d();
                void cb_res_3_e();
                void cb_res_3_h();
                void cb_res_3_l();
                void cb_res_3_addr_hl();
                void cb_res_3_a();
                void cb_res_4_b();
                void cb_res_4_c();
                void cb_res_4_d();
                void cb_res_4_e();
                void cb_res_4_h();
                void cb_res_4_l();
                void cb_res_4_addr_hl();
                void cb_res_4_a();
                void cb_res_5_b();
                void cb_res_5_c();
                void cb_res_5_d();
                void cb_res_5_e();
                void cb_res_5_h();
                void cb_res_5_l();
                void cb_res_5_addr_hl();
                void cb_res_5_a();
                void cb_res_6_b();
                void cb_res_6_c();
                void cb_res_6_d();
                void cb_res_6_e();
                void cb_res_6_h();
                void cb_res_6_l();
                void cb_res_6_addr_hl();
                void cb_res_6_a();
                void cb_res_7_b();
                void cb_res_7_c();
                void cb_res_7_d();
                void cb_res_7_e();
                void cb_res_7_h();
                void cb_res_7_l();
                void cb_res_7_addr_hl();
                void cb_res_7_a();
                void cb_set_0_b();
                void cb_set_0_c();
                void cb_set_0_d();
                void cb_set_0_e();
                void cb_set_0_h();
                void cb_set_0_l();
                void cb_set_0_addr_hl();
                void cb_set_0_a();
                void cb_set_1_b();
                void cb_set_1_c();
                void cb_set_1_d();
                void cb_set_1_e();
                void cb_set_1_h();
                void cb_set_1_l();
                void cb_set_1_addr_hl();
                void cb_set_1_a();
                void cb_set_2_b();
                void cb_set_2_c();
                void cb_set_2_d();
                void cb_set_2_e();
                void cb_set_2_h();
                void cb_set_2_l();
                void cb_set_2_addr_hl();
                void cb_set_2_a();
                void cb_set_3_b();
                void cb_set_3_c();
                void cb_set_3_d();
                void cb_set_3_e();
                void cb_set_3_h();
                void cb_set_3_l();
                void cb_set_3_addr_hl();
                void cb_set_3_a();
                void cb_set_4_b();
                void cb_set_4_c();
                void cb_set_4_d();
                void cb_set_4_e();
                void cb_set_4_h();
                void cb_set_4_l();
                void cb_set_4_addr_hl();
                void cb_set_4_a();
                void cb_set_5_b();
                void cb_set_5_c();
                void cb_set_5_d();
                void cb_set_5_e();
                void cb_set_5_h();
                void cb_set_5_l();
                void cb_set_5_addr_hl();
                void cb_set_5_a();
                void cb_set_6_b();
                void cb_set_6_c();
                void cb_set_6_d();
                void cb_set_6_e();
                void cb_set_6_h();
                void cb_set_6_l();
                void cb_set_6_addr_hl();
                void cb_set_6_a();
                void cb_set_7_b();
                void cb_set_7_c();
                void cb_set_7_d();
                void cb_set_7_e();
                void cb_set_7_h();
                void cb_set_7_l();
                void cb_set_7_addr_hl();
                void cb_set_7_a();

                // registers
                union {
                        struct {
                                std::uint8_t unused       : 4{0}; // BITS 4
                                std::uint8_t carry        : 1{1}; // BITS 1
                                std::uint8_t half_carry   : 1{1}; // BITS 1
                                std::uint8_t n_flag       : 1{0}; // BITS 1
                                std::uint8_t zero         : 1{1}; // BITS 1
                                std::uint8_t a{0x01};
                        };
                        std::uint16_t af;
                };
                union {
                        struct {
                                std::uint8_t c{0x13};
                                std::uint8_t b{0x00};
                        };
                        std::uint16_t bc;
                };
                union {
                        struct {
                                std::uint8_t e{0xD8};
                                std::uint8_t d{0X00};
                        };
                        std::uint16_t de;
                };
                union {
                        struct {
                                std::uint8_t l{0x4D};
                                std::uint8_t h{0x01};
                        };
                        std::uint16_t hl;
                };
                std::uint16_t pc{0x0100};
                std::uint16_t sp{0xFFFE};
                float internal_audio_accumulator{0.0f};
                std::shared_ptr<Bus> bus{};
                std::shared_ptr<PPU> ppu{};
                std::shared_ptr<APU> apu{};
                struct OpCodeHandler{
                        std::uint8_t cycles{};
                        std::string mnemonic{};
                        std::function<void()> execute{};
                };
                std::vector<OpCodeHandler> lookup_table{};
                std::vector<OpCodeHandler> cb_lookup_table{};
                std::uint16_t div_addr{0xFF04};
                std::uint16_t tima_addr{0xFF05};
                std::uint16_t tma_addr{0xFF06};
                std::uint16_t tac_addr{0xFF07};
                std::uint16_t div_counter{0};
                std::uint16_t tima_counter{0};
                bool interrupt_master_enable{false};
                bool enable_interrupt_next_cycle{false};
                bool is_halted{false};
};
#endif
